# Generated by Django 5.0.6 on 2024-05-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_users_notifications_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(blank=True, choices=[('GENERALISTE', 'Généraliste'), ('CARDIOLOGUE', 'Cardiologue'), ('DERMATOLOGUE', 'Dermatologue'), ('GYNECOLOGUE', 'Gynécologue'), ('NEUROLOGUE', 'Neurologue'), ('OPHTALMOLOGUE', 'Ophtalmologue'), ('ORL', 'ORL'), ('PEDIATRE', 'Pédiatre'), ('PSYCHIATRE', 'Psychiatre'), ('RADIOLOGUE', 'Radiologue'), ('CHIRURGIEN', 'Chirurgien')], max_length=70, null=True),
        ),
    ]
