# Generated by Django 5.0.6 on 2024-05-22 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Programme', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('CONFIRME', 'Confirme'), ('ANNULE', 'Annuler'), ('EN_ATTENTE', 'En Attente'), ('REPORTER', 'Reporter')], default='EN_ATTENTE', max_length=20)),
                ('motif', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='Users.medecin')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='Users.patient')),
                ('programme', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='Programme.programme')),
            ],
        ),
    ]
